import { CheckCircle2, Circle, Clock, Calendar, Loader2 } from 'lucide-react';
import { useState, useEffect } from 'react';
import { getLearningPath } from '../api';

interface AdaptiveLearningPathProps {
  onStartLearning: () => void;
}

interface Topic {
  title: string;
  status: 'completed' | 'in-progress' | 'upcoming';
  duration: string;
  revisions: string[];
}

export function AdaptiveLearningPath({ onStartLearning }: AdaptiveLearningPathProps) {
  const [topics, setTopics] = useState<Topic[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => { loadPath(); }, []);

  const loadPath = async () => {
    try {
      const data = await getLearningPath();
      setTopics((data.path || []).slice(0, 8).map((t: any) => ({
        title: t.title, status: t.status, duration: t.duration,
        revisions: (t.revisions || []).map((r: any) => r.date || r)
      })));
    } catch {
      setTopics([
        { title: 'TypeScript Basics', status: 'completed', duration: '2 hours', revisions: ['Day 1', 'Day 3', 'Day 7'] },
        { title: 'Advanced Types', status: 'in-progress', duration: '3 hours', revisions: ['Day 1', 'Day 3'] },
        { title: 'React with TypeScript', status: 'upcoming', duration: '4 hours', revisions: [] },
        { title: 'State Management Patterns', status: 'upcoming', duration: '3 hours', revisions: [] },
        { title: 'Testing Best Practices', status: 'upcoming', duration: '2.5 hours', revisions: [] }
      ]);
    } finally { setLoading(false); }
  };

  if (loading) return <div className="min-h-screen flex items-center justify-center bg-transparent"><Loader2 className="w-10 h-10 animate-spin text-indigo-400" /></div>;

  return (
    <div className="min-h-screen flex items-center justify-center px-6 py-12 bg-transparent">
      <div className="w-full max-w-4xl rounded-[32px] p-12 backdrop-blur-[40px] border border-white/10 shadow-[0_0_80px_rgba(0,0,0,0.5)]" style={{ background: 'rgba(15, 23, 42, 0.7)' }}>
        <div className="text-center mb-12 relative">
          <div className="absolute -top-10 left-1/2 -translate-x-1/2 w-40 h-40 bg-indigo-500/10 rounded-full blur-[60px]" />
          <h2 className="bg-gradient-to-r from-white to-indigo-300 bg-clip-text text-transparent" style={{ fontFamily: 'Inter, sans-serif', fontSize: '36px', fontWeight: 800, marginBottom: '8px' }}>Neural Learning Path</h2>
          <p className="text-slate-400" style={{ fontSize: '16px' }}>Adaptive curriculum generated by AI based on your cognitive profile</p>
        </div>

        <div className="relative space-y-8 mb-12">
          <div className="absolute left-[15px] top-4 bottom-4 w-[2px]" style={{ background: 'linear-gradient(180deg, #4F46E5 0%, #06B6D4 100%)', opacity: 0.3 }} />
          {topics.map((topic, idx) => {
            const colors = {
              completed: { main: '#10B981', bg: 'rgba(16, 185, 129, 0.1)', border: 'rgba(16, 185, 129, 0.2)' },
              'in-progress': { main: '#818CF8', bg: 'rgba(129, 140, 248, 0.1)', border: 'rgba(129, 140, 248, 0.2)' },
              upcoming: { main: '#64748B', bg: 'rgba(100, 116, 139, 0.1)', border: 'rgba(100, 116, 139, 0.2)' }
            };
            const color = colors[topic.status as keyof typeof colors] || colors.upcoming;

            return (
              <div key={idx} className="relative pl-12 group">
                <div className="absolute left-0 w-8 h-8 rounded-full flex items-center justify-center z-10 transition-transform group-hover:scale-110" style={{ background: color.main, boxShadow: `0 0 20px ${color.main}50` }}>
                  {topic.status === 'completed' ? <CheckCircle2 className="w-5 h-5 text-white" /> : <Circle className="w-5 h-5 text-white" fill={topic.status === 'in-progress' ? 'currentColor' : 'none'} />}
                </div>
                <div className="rounded-[24px] p-6 transition-all duration-300 hover:shadow-2xl hover:-translate-y-1 relative overflow-hidden group" style={{ background: 'rgba(30, 41, 59, 0.6)', border: `1px solid ${color.border}` }}>
                  <div className="absolute inset-0 bg-gradient-to-br from-white/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity" />
                  <div className="flex items-start justify-between mb-4 relative z-10">
                    <div className="flex-1">
                      <h3 style={{ fontFamily: 'Inter, sans-serif', fontSize: '20px', fontWeight: 700, color: '#F8FAFC', marginBottom: '6px' }}>{topic.title}</h3>
                      <div className="flex items-center gap-5">
                        <div className="flex items-center gap-1.5 text-slate-400 font-medium"><Clock className="w-4 h-4" /><span style={{ fontSize: '14px' }}>{topic.duration}</span></div>
                        {topic.status !== 'upcoming' && (
                          <div className="px-3 py-1 rounded-full shadow-lg" style={{ background: color.bg, border: `1px solid ${color.border}` }}>
                            <span style={{ fontSize: '11px', fontWeight: 800, color: color.main, textTransform: 'uppercase', letterSpacing: '0.05em' }}>{topic.status === 'completed' ? 'Synced' : 'Active'}</span>
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                  {topic.revisions.length > 0 && (
                    <div className="flex items-center gap-3 mt-5 pt-5 border-t border-white/5 relative z-10">
                      <Calendar className="w-4 h-4 text-slate-500" />
                      <span className="text-slate-500" style={{ fontSize: '13px', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.05em' }}>Revision Points:</span>
                      <div className="flex flex-wrap gap-2">
                        {topic.revisions.map((rev: string, i: number) => (
                          <div key={i} className="px-3 py-1 rounded-lg shadow-inner" style={{ background: 'rgba(6, 182, 212, 0.1)', border: '1px solid rgba(6, 182, 212, 0.2)' }}>
                            <span style={{ fontSize: '11px', fontWeight: 700, color: '#2DD4BF' }}>{rev}</span>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              </div>
            );
          })}
        </div>

        <button onClick={onStartLearning} className="w-full py-4.5 rounded-[18px] transition-all duration-300 hover:scale-[1.02] hover:shadow-[0_0_40px_rgba(129,140,248,0.4)] shadow-xl" style={{ background: 'linear-gradient(135deg, #4F46E5 0%, #818CF8 100%)', color: 'white', fontSize: '16px', fontWeight: 700 }}>
          Initialize Protocol
        </button>
      </div>
    </div>
  );
}
